# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  このIssueは、長い間活動が見られません。活動が見られないため、自動的に古いIssueとしてマークされています。
  もし、これ以上の活動が見られなければ、自動的にクローズされます。
  あなたの貢献に感謝いたします。
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
